# Generated by Django 3.2.3 on 2021-05-19 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('fechainicio', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.persona')),
            ],
        ),
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('1', 'titular'), ('2', 'asistente')], max_length=15)),
                ('rut_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.persona')),
            ],
        ),
    ]
